# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b474aea618310a38a257439d367eeb8d3a8bd0beaf5f42ba85ca687c62c49fd470183a51b7b0270de9773cf79d493f41f0e7d1526a4f7952e277664ad2678d7

test:
  secret_key_base: bc9bee211bfe5a57d7d16f5df8024b1f1dc89560c86e5e0012c01842b343b2cd62273eafc10c255b879d6580679acda92b654a801a2cc7c9e234536cc4d34c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
